- persist/src/main/resources/db/migration/V1__Initial_Import.sql
Create new db tables required for milestone 1. See [here](https://lucid.app/lucidchart/2e440718-aca6-4efa-adb1-4fc6112bcf42/view?page=0_0#?folder_id=home&browser=icon) for an overview of our database. All tables but the sites, sites entry and stewardship tables should be in this PR.
> Add tables

- .travis.yml
- common/src/main/java/com/codeforcommunity/enums/PrivilegeLevel.java
- common/src/main/java/com/codeforcommunity/enums/TeamRole.java
- common/src/main/resources/properties/server.properties.example
- persist/pom.xml
- persist/src/main/resources/db/migration/V1__Initial_Import.sql
The final edits to the db schema as discussed. For a visual overview see here: [https://lucid.app/lucidchart/2e440718-aca6-4efa-adb1-4fc6112bcf42/view](https://lucid.app/lucidchart/2e440718-aca6-4efa-adb1-4fc6112bcf42/view)
> Edits to final db schema

- api/src/main/java/com/codeforcommunity/api/IProtectedUserProcessor.java
- api/src/main/java/com/codeforcommunity/dto/ApiDto.java
- api/src/main/java/com/codeforcommunity/dto/user/ChangePrivilegeLevelRequest.java
- api/src/main/java/com/codeforcommunity/exceptions/SamePrivilegeLevelException.java
- api/src/main/java/com/codeforcommunity/rest/FailureHandler.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedUserRouter.java
- common/src/main/java/com/codeforcommunity/enums/PrivilegeLevel.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedUserProcessorImpl.java
Added the last missing route for the user router, change privilege level.
> Finish user router

- api/src/main/java/com/codeforcommunity/rest/ApiRouter.java
Made map routes unprotected since people need to be able see the map on the home page
> Opened up map routes to everyone

- api/src/main/java/com/codeforcommunity/api/IProtectedUserProcessor.java
- api/src/main/java/com/codeforcommunity/dto/user/ChangeUsernameRequest.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedUserRouter.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedUserProcessorImpl.java
https://docs.c4cneu.com/sftt/sftt-api-spec/#change-username
> Added change username route described in the docs

- api/src/main/java/com/codeforcommunity/api/IProtectedUserProcessor.java
- api/src/main/java/com/codeforcommunity/dto/user/DeleteUserRequest.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedUserRouter.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedUserProcessorImpl.java
No changes to API spec required, already looked like this
> Changed delete user route from DELETE to POST request

- api/src/main/java/com/codeforcommunity/api/ISiteProcessor.java
- api/src/main/java/com/codeforcommunity/rest/ApiRouter.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/SiteRouter.java
- service/src/main/java/com/codeforcommunity/ServiceMain.java
- service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
@reviewer Docs say `sitesRouter`, implemented as `siteRouter`. Please comment your preference
> Added the site router to the backend

- api/src/main/java/com/codeforcommunity/api/ISiteProcessor.java
- api/src/main/java/com/codeforcommunity/dto/site/RecordStewardshipRequest.java
- api/src/main/java/com/codeforcommunity/exceptions/WrongFavoriteStatusException.java
- api/src/main/java/com/codeforcommunity/rest/FailureHandler.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/SiteRouter.java
- service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
Ticket link: [https://code4community-team.monday.com/boards/925293934/pulses/1185013981](https://code4community-team.monday.com/boards/925293934/pulses/1185013981)
> Created three new routes on site router

- api/src/main/java/com/codeforcommunity/dto/map/GeometryPoint.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedUserProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/TeamsProcessorImpl.java
- Added `execute()` and `store()` calls to SQL calls to delete DB records, where they were previously missing.
- Added some previously repeated code to the `userExistsCheck()` method.
- Ran `mvn clean install`, which reformatted some of the code.
- Fixed some code in several invocations of exception constructors that would have thrown `NullPointerException`s.
See [ticket 1](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1258025133) and [ticket 2](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1276837946) on Monday.
> Fix delete bugs

- service/src/main/java/com/codeforcommunity/processor/TeamsProcessorImpl.java
https://code4community-team.monday.com/boards/925293934/pulses/1167889035
> Fixed goal value in getTeam

- api/src/main/java/com/codeforcommunity/dto/user/UserDataResponse.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedUserProcessorImpl.java
https://code4community-team.monday.com/boards/925293934/pulses/1262683746
> Added username to getUserData response

- service/src/main/java/com/codeforcommunity/processor/ProtectedUserProcessorImpl.java
https://code4community-team.monday.com/boards/925293934/pulses/1270342065
> Fixed admins being able to demote super admins bug

- service/src/main/java/com/codeforcommunity/processor/MapProcessorImpl.java
Resolved an error where nullUserRecords was trying to select from the users table even though the Users table was not in the FROM statement. Now that table is selecting from Entry_Usernames.
Also resolved a stackoverflow error in mergeSorted by changing the function from recursive to iterative.
> changed from statement for entry usernames and made mergeSorted iterative

- api/src/main/java/com/codeforcommunity/dto/site/RecordStewardshipRequest.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
Fixed [issue](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1323567094) where stewardship activities could not be recorded by setting the stewardship record's siteId.
> Fix record stewardship

- api/src/main/java/com/codeforcommunity/dto/map/SiteFeatureProperties.java
- api/src/main/java/com/codeforcommunity/dto/map/TimeStamp.java
- service/src/main/java/com/codeforcommunity/processor/MapProcessorImpl.java
Changed the siteGeoJson query to not look for username. Not a huge performance increase but enough to be significant, particularly on the longest response
old:
new:
> removed username from siteGeoJSON

- .github/workflows/deploy.yml
- common/src/main/resources/properties/server.properties.example
- deploy.py
I'm not totally positive if this fixed everything but I copied the configuration from the llb build files.
Not sure how to access the secrets in ElasticBeanstalk so there may need to be an edit there too
> edit configuration to include email

- common/src/main/resources/properties/server.properties.example
Updated the base url for emails
> updated base url

- service/src/main/java/com/codeforcommunity/dataaccess/AuthDatabaseOperations.java
Fix for a dev alert error for blacklisted tokens
> used same fix on backend-scaffold

- api/src/main/java/com/codeforcommunity/api/ITeamsProcessor.java
- api/src/main/java/com/codeforcommunity/rest/FailureHandler.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/TeamsRouter.java
- service/src/main/java/com/codeforcommunity/processor/TeamsProcessorImpl.java
Small updates to backend to match dev docs
> Wt.dev docs update

- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
[ClickUp Ticket](https://app.clickup.com/t/200h9xx)
Ensures the site entry record created when updating a site has a unique ID by setting its ID to the max existing ID + 1.
> Ensure new site entries record has a valid ID

- persist/src/main/resources/db/migration/V2__Add_Sites.sql
- persist/src/main/resources/db/migration/V3_10__AddTreeName.sql
Added a tree_name field to the site_entries table.
> JH.LJ Add Tree Name to Site Entries

- common/src/main/resources/properties/server.properties.example
[ClickUp](https://app.clickup.com/t/2nuqbb1)
Changes the email address that emails are sent from, as per SFTT's request. (Will update the send password after this PR is merged)
Tested that no errors were caused and that I received the email locally.
> Update email sender address

- common/src/main/resources/emails/WelcomeEmail.html
- service/src/main/java/com/codeforcommunity/requester/Emailer.java
[ClickUp Ticket](https://app.clickup.com/t/20hrd9g)
- updated content according to SFTT request
- renamed loginUrl to frontendUrl since the link is to the base url, not the login page
New Email
> Update Welcome Email Content

- api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java
- api/src/main/java/com/codeforcommunity/dto/site/ParentAdoptSiteRequest.java
- api/src/main/java/com/codeforcommunity/dto/site/ParentRecordStewardshipRequest.java
- api/src/main/java/com/codeforcommunity/dto/site/RecordStewardshipRequest.java
- api/src/main/java/com/codeforcommunity/dto/site/SiteEntry.java
- api/src/main/java/com/codeforcommunity/dto/site/StewardshipActivity.java
- api/src/main/java/com/codeforcommunity/dto/site/UploadSiteImageRequest.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java
- persist/src/main/resources/db/migration/V4_2__AddSiteImages.sql
- service/src/main/java/com/codeforcommunity/dataaccess/AuthDatabaseOperations.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
> Add site images table (and code cleanup)

- pom.xml
(No relevant ClickUp ticket)
For debugging purposes (there's more detailed output in version 7.2.0 when `mvn clean install` fails)
> Update Flyway version to 7.2.0

- persist/src/main/resources/db/migration/V4_2__AddSiteImages.sql
This reverts commit 42624d5f429344ac1e1b59428589aa762fc4bd12.
> Revert "Delete add sites image table SQL script (#135)"

- pom.xml
- service/pom.xml
> 📦 build: moved depenencies to top level pom + reformat

- api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java
- api/src/main/java/com/codeforcommunity/dto/site/AddSitesRequest.java
- api/src/main/java/com/codeforcommunity/rest/RestFunctions.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
Fix broken addSites route and add AddSitesRequest DTO
> Fix addSites bug and add AddSitesRequest

- api/src/main/java/com/codeforcommunity/dto/site/CSVSiteUpload.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
> Add sites CSV neighborhoodId to neighborhood

- api/src/main/java/com/codeforcommunity/api/IProtectedUserProcessor.java
- api/src/main/java/com/codeforcommunity/dto/user/GetChildUserResponse.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedUserRouter.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedUserProcessorImpl.java
[ClickUp Ticket](https://app.clickup.com/t/862hya0u3)
Parent accounts are able to see who their child accounts are. Returns firstName, lastName, username, and email of the parent's child accounts. 
Added the getChildUser route and the getChildUserResponse DTO.
We used Postman to call the GET request and ensure that the child accounts of a parent are returned in the response body. When the parent had no child accounts, the GET request was called again and a empty response body was returned.
> added getChildUser route

- .github/workflows/deploy-cambridge.yml
> Add deploy-cambridge.yml

- .github/workflows/deploy-cambridge.yml
> Deploy to cambridge

- api/src/main/java/com/codeforcommunity/api/IProtectedUserProcessor.java
- api/src/main/java/com/codeforcommunity/dto/site/AddSitesRequest.java
- api/src/main/java/com/codeforcommunity/dto/site/CSVSiteUpload.java
- persist/src/main/resources/db/migration/V4_3__AddSiteEntriesCreatedAt.sql
- service/src/main/java/com/codeforcommunity/processor/ProtectedUserProcessorImpl.java
No relevant ClickUp ticket
Add a new column to the `SITE_ENTRIES` table called `created_at` so that the existing `updated_at` column can be used for when the site entry was last modified (in the edit site entry route, for instance)
> Add migration script for adding created_at to SITE_ENTRIES and code formatting

- api/src/main/java/com/codeforcommunity/dto/imports/SiteImport.java
> Temporarily remove address check to upload Cambridge data

- common/src/main/resources/emails/Email.html
- service/src/main/java/com/codeforcommunity/requester/Emailer.java
> Emailer backend fixes

- api/src/main/java/com/codeforcommunity/dto/site/FilterSitesRequest.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
> Fix filter sites route

- api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
[ClickUp Ticket](https://app.clickup.com/t/3ucuvx8)
Allows admins to edit site existing entries by specifying an entry Id and the updated values
Uses the existing UpdateSiteRequest (name misleading) as dto, some filter site merge conflicts resolved.
Made a POST request in Postman: http://localhost:8081/api/v1/protected/sites/edit_entry/1
First with invalid access key to ensure admin only access.
Made a request with valid access key to update all values to null-- all values updated correctly, including updating userId and updatedAt
> Edit site entries

- api/src/main/java/com/codeforcommunity/dto/site/FilterSitesRequest.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
> Ah.filter sites activity counts

- api/src/main/java/com/codeforcommunity/dto/site/FilterSitesRequest.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
> edit activity counts

- .github/workflows/deploy-cambridge.yml
- .github/workflows/deploy.yml
- deploy.py
- service/src/main/java/com/codeforcommunity/processor/AbstractProcessor.java
> Allow Cambridge to send emails

- .github/workflows/deploy-cambridge.yml
- .github/workflows/deploy.yml
- deploy.py
> Revert cambridge email changes

- .github/workflows/deploy-cambridge.yml
- .github/workflows/deploy.yml
- deploy.py
- service/src/main/java/com/codeforcommunity/processor/AbstractProcessor.java
> Revert isSftt and revert reverting Cambridge email changes

- api/src/main/java/com/codeforcommunity/dto/site/CSVSiteUpload.java
> Add plantingDate to CSVSiteUpload DTO

- api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java
- api/src/main/java/com/codeforcommunity/api/ISiteProcessor.java
- api/src/main/java/com/codeforcommunity/dto/map/SiteFeatureProperties.java
- api/src/main/java/com/codeforcommunity/dto/site/AddSiteRequest.java
- api/src/main/java/com/codeforcommunity/dto/site/CSVSiteUpload.java
- api/src/main/java/com/codeforcommunity/dto/site/EditSiteRequest.java
- api/src/main/java/com/codeforcommunity/dto/site/FilterSitesRequest.java
- api/src/main/java/com/codeforcommunity/dto/site/FilterSitesResponse.java
- api/src/main/java/com/codeforcommunity/dto/site/GetSiteResponse.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/SiteRouter.java
- common/src/main/java/com/codeforcommunity/enums/SiteOwner.java
- persist/src/main/resources/db/migration/V4_5__AddSitesOwner.sql
- service/src/main/java/com/codeforcommunity/processor/MapProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
- service/src/main/java/com/codeforcommunity/requester/Emailer.java
> Add owner to site

- api/src/main/java/com/codeforcommunity/dto/site/CSVSiteUpload.java
> Add owner to add sites route

- .github/workflows/deploy-cambridge.yml
- .github/workflows/deploy.yml
> Change deploy names

- common/src/main/java/com/codeforcommunity/enums/SiteOwner.java
> Fix SiteOwner from() bug

- common/src/main/java/com/codeforcommunity/enums/SiteOwner.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
> Better error handling for site owner in CSV sites upload

- .github/workflows/deploy.yml
- api/src/main/java/com/codeforcommunity/dto/site/AddSiteRequest.java
> Fix site lat/lng overflow error

- api/src/main/java/com/codeforcommunity/dto/site/EditSiteRequest.java
> fix lat/lng overflow for editing sites

- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
> Redeploy Cambridge

- README.md
> Trigger Cambridge redeploy

- api/src/main/java/com/codeforcommunity/dto/site/StewardshipActivity.java
> try activity date fix

- api/src/main/java/com/codeforcommunity/dto/report/Stewardship.java
- api/src/main/java/com/codeforcommunity/dto/site/EditStewardshipRequest.java
- api/src/main/java/com/codeforcommunity/dto/site/ParentRecordStewardshipRequest.java
- api/src/main/java/com/codeforcommunity/dto/site/RecordStewardshipRequest.java
- api/src/main/java/com/codeforcommunity/dto/site/StewardshipActivity.java
- persist/src/main/resources/db/migration/V4_6__AddStewardshipWateringBag.sql
- service/src/main/java/com/codeforcommunity/processor/ProtectedReportProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
[GH Projects ticket](https://github.com/Code-4-Community/speak-for-the-trees-backend-v2/issues/192)
Resolves #192 
See also https://github.com/Code-4-Community/speak-for-the-trees-frontend/pull/256
Add "installed watering bag" as a new activity to track for stewardships
- Adds a new column "installedWateringBag" to the stewardship table
- Added new field `installedWateringBag` to stewardship DTOs
- Updated routes to use these fields and n
- Verified the record/edit stewardship route correctly saves `installedWateringBag` status
- Verified the get stewardship route correctly retrieves `installedWateringBag` status
- Verified stewardship report methods correctly retrieve and format `installedWateringBag` status
> Ah.stewardship watering bag

- api/src/main/java/com/codeforcommunity/dto/imports/SiteImport.java
- api/src/main/java/com/codeforcommunity/dto/site/SiteEntry.java
- service/src/main/java/com/codeforcommunity/processor/ImportProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
> update site imports to take site owner

- .github/workflows/deploy-cambridge.yml
- deploy.py
- service/src/main/java/com/codeforcommunity/processor/ProtectedEmailerProcessorImpl.java
- service/src/main/java/com/codeforcommunity/requester/S3Requester.java
> update s3 dirs to split with dev/prod

- api/src/main/java/com/codeforcommunity/rest/subrouter/SiteRouter.java
- service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
> fix null ptr when getting site images

- service/src/main/java/com/codeforcommunity/requester/S3Requester.java
> Update S3Requester.java - fix image uploading to use correct url

- api/src/main/java/com/codeforcommunity/dto/site/SiteEntryImage.java
- service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
> update get site route to get image uploader id

- api/src/main/java/com/codeforcommunity/dto/site/AddSiteRequest.java
- api/src/main/java/com/codeforcommunity/dto/site/CSVSiteUpload.java
- api/src/main/java/com/codeforcommunity/dto/site/SiteEntry.java
- api/src/main/java/com/codeforcommunity/dto/site/UpdateSiteRequest.java
- persist/src/main/resources/db/migration/V5__AddSiteEntriesBostonId.sql
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
- service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
> add migration + new fields

- service/src/main/java/com/codeforcommunity/requester/Emailer.java
> whitespace deploy to update env variables

- api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java
- api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
> change body to request param

- api/src/main/java/com/codeforcommunity/dto/neighborhoods/SendEmailRequest.java
- service/src/main/java/com/codeforcommunity/processor/ProtectedNeighborhoodsProcessorImpl.java
> fix: allows emailer to send w/o attachments
