service/src/main/java/com/codeforcommunity/processor/ReservationProcessorImpl.java, service/src/test/java/com.codeforcommunity/processor/ProcessorImplTest.java, service/src/test/java/com.codeforcommunity/processor/ReservationProcessorImplTest.java
To test the `basicChecks()` method the JooqMock class has to be updated to support mocking fetchExists calls.
I couldn't get maven to properly run the `setup()` method with the `@BeforeEach` annotation. I mention in a TODO but the solution is in [this stack overflow post](https://stackoverflow.com/questions/51382356/maven-does-not-run-beforeeach-methods-while-running), the problem is we currently don't specify our maven surefire plugin explicitly and I am too lazy to tackle that right now.
=> Add unit tests for reservation processor

service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
Fixed [issue](https://code4community-team.monday.com/boards/925293934/views/18904377/pulses/1323574183) where a user can adopt a site that has been adopted by someone else by changing `isAlreadyAdopted` to check if any record for the site exists, regardless of who has adopted it.
=> Fix can adopt already adopted

api/src/main/java/com/codeforcommunity/dto/site/RecordStewardshipRequest.java, service/src/main/java/com/codeforcommunity/processor/MapProcessorImpl.java
calling `getSiteGeoJson()` takes about 5000ms when load tested on @willmt80 's computer with ~11,000 sites. When called multiple times in succession the Vert.x event loop is blocked (basically it suffers the same problem as node.js when the app is running on a single verticle). Each 5000ms request gets queued up and eventually the event loop gets too backed up and some requests get dropped.
By keeping an in-memory cache of previous results with a TTL of 1-2 times the mean response time, we get rid of "queueing" problem, which means nothing will get backed up and we shouldn't get dropped requests.
I create a private cache class for the map processor (we could make it generic if we wanted but we only cache in one place so 🤷 ) and give it an expiry date. In `getSiteGeoJson()` we first check …
=> Add In-Memory Cache for getSiteGeoJSON

api/src/main/java/com/codeforcommunity/dto/map/SiteFeatureProperties.java, service/src/main/java/com/codeforcommunity/processor/MapProcessorImpl.java
Edited the map site query in order to prevent repeating sites from appearing on the map.
Instead of checking if a timestamp is in a subquery, the query uses a series of joins.
The latency for the longest request is slightly longer than before but the mean latency is lower.
Here is an example of the old output on the frontend
And the same spot with the new query
=> Unique site entries on map

service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
Closes #65.
Changed the query, made sure frontend shows the most recent site on the tree page:
Before
After
=> Site entries are ordered from most to least recent

api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java, api/src/main/java/com/codeforcommunity/dto/site/AddSiteRequest.java, api/src/main/java/com/codeforcommunity/dto/site/AddSitesRequest.java, api/src/main/java/com/codeforcommunity/dto/site/UpdateSiteRequest.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
https://app.clickup.com/t/1dk48g9
Creates a route where admins can create more than one site at a time. Uses logic already defined to add individual sites. 
Also modified some of the constraints on add site and update site such as defaulting boolean values to false and making block_id an optional field.
Originally attempted to handle csv parsing and processing on the server, however given the small size of the the expected csvs and familiarity with csv parsing in Typescript, decided to handle csv processing on the frontend.
=> Wt.add sites

service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
Ticket: https://app.clickup.com/t/1dk490u
Ensures that the user has adopted the given site before recording a stewardship activity. Returns a 400 exception if they are not the adopter.
The check if user has adopted site method and exception already existed, just added them to the record stewardship method
=> added check to ensure user has adopted a particular site for recording stewardship

api/src/main/java/com/codeforcommunity/dto/site/GetSiteResponse.java, service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
Fixed the GetSiteResponse object to use a neighborhood's ID rather than its name, and changed SiteProcessorImpl to pass the correct value to the GetSiteResponse constructor. @jhylisa666
=> Fixed the GetSiteResponse object

api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
@jhylisa666 and I worked on a new route that allows admins to force unadopt the sites of standard users and allows super admins to force unadopt the sites of standard users, admins, and other super admins.
In the course of modifying the ProtectedSiteProcessor, we also added a new utility method `isAdmin(PrivilegeLevel)` which returns a boolean indicating whether a user with the given privilege level is an admin or super admin.
Route is accessible via:
`POST api/v1/protected/sites/:site_id/force_unadopt`
=> Jh.lj Force Unadopt Route for Admins

persist/src/main/resources/db/migration/V3_11__AddParentAccount.sql
Worked with @chromium-52 to add migration script `V3_11__AddParentAccount.sql` that creates a new table `parent_accounts` that links a parent user account with a child user account. 
[ClickUp Ticket](https://app.clickup.com/t/27pkzc1)
=> Created migration script for adding parent account table

api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java, api/src/main/java/com/codeforcommunity/dto/site/NameSiteEntryRequest.java, api/src/main/java/com/codeforcommunity/exceptions/LinkedResourceDoesNotExistException.java, api/src/main/java/com/codeforcommunity/rest/FailureHandler.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
Created a route for renaming the most recent site entry that exists for a given site id. The site must be adopted by the calling user.
Route accessible via:
`POST api/v1/protected/sites/:site_id/name_entry`
Also created a LinkedResourceDoesNotExist exception in order to give more information in the case of a resource not existing that on its own does not have a meaningful id. The exception responds with a `400 BAD REQUEST` status. An example of the error message is shown below:
[ClickUp Ticket](https://app.clickup.com/t/22gq4y3)
=> Route to name most recent site entry for an adopted site

common/src/main/resources/emails/PasswordChangeRequest.html
[ClickUp Ticket](https://app.clickup.com/t/2pwzzhx)
Updates the password change request email template for a more aesthetic user experience.
- Changed styling according to the design provided by SFTT
- Fixed broken image links
- Created a new S3 bucket and CloudFront distribution to host new email images (and other public content)
- Enabled public access through CloudFront Origin Access Identity ([more information + why](https://www.stormit.cloud/post/cloudfront-origin-access-identity))
- Used divs instead of images where possible for greater stability
- Cleaned up HTML to improve readability
- Followed IntelliJ suggestions to use CSS shorthands + update outdated attributes
- Added comments to break up sections
- Formatted HTML using …
=> Update forgot password email template

service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
Explicitly specify the ID of the `siteEntriesRecord` when creating one as it was giving me a duplicate primary key error without it when I was testing the add site form in the frontend (similar to line 206 of `ProtectedSiteProcessorImpl.java` with `sitesRecord`).
=> Specify site ID in addSite route

api/src/main/java/com/codeforcommunity/dto/site/RecordStewardshipRequest.java
When parsing and saving stewardship activity dates, change the timezone from the default (UTC) timezone to Boston time (GMT-4).
=> Change stewardship activity date field timezone from UTC to EST

api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java, api/src/main/java/com/codeforcommunity/dto/site/ParentAdoptSiteRequest.java, api/src/main/java/com/codeforcommunity/dto/site/ParentRecordStewardshipRequest.java, api/src/main/java/com/codeforcommunity/dto/site/RecordStewardshipRequest.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
Worked with @mayazeldin to create a new route to handle parents adopting sites for a specified child and a new route to handle parents recording stewardship activities for a specified child.
Route to handle parent adopt site for child:
`POST api/v1/protected/sites/:site_id/parent_adopt`
Route to handle parent record stewardship for child:
`POST api/v1/protected/sites/:site_id/parent_record_stewardship`
Created additional helper methods (`checkParent`, `isParent`) for the `ProtectedSiteProcessor` for determining whether a user is the parent of a given child.
[ClickUp Ticket](https://app.clickup.com/t/29xd1x4)
=> Child Account Functionality

api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java, api/src/main/java/com/codeforcommunity/dto/site/EditStewardshipRequest.java, api/src/main/java/com/codeforcommunity/dto/site/RecordStewardshipRequest.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
[ClickUp ticket](https://app.clickup.com/t/3ucv22f)
Add route to allow admins and tree site owners to edit existing stewardship activities
Route: ```POST api/v1/protected/sites/edit_stewardship/:site_id```
- Add new class EditStewardShipRequest 
- Update ProtectedSiteRouter, ProtectedSiteProcessorImpl to handle edit stewardship requests
- Request to edit existing record as admin - database correctly reflects changes
- Request to edit existing record as non-admin owner - database correctly reflects changes
- Request to edit nonexistent record - returns proper error status + message
- Request to edit existing record as non-admin/non-owner - returns proper error status + message
- Request to edit existing record with malformed body - returns proper error status + message
=> Add Edit Stewardship Route

api/src/main/java/com/codeforcommunity/dto/site/GetSiteResponse.java, api/src/main/java/com/codeforcommunity/dto/site/SiteEntry.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
Modify the get site route so that it also returns the tree name for each site entry.
Modify the name site entry route so that passing in an empty string deletes its name (i.e. sets is to `null`).
=> Update get site and name site entry routes

service/src/main/java/com/codeforcommunity/dataaccess/AuthDatabaseOperations.java, service/src/main/java/com/codeforcommunity/processor/ProtectedUserProcessorImpl.java
ClickUp ticket: https://app.clickup.com/t/47u12vb
Change checking for email equality to always be case insensitive.
Tested that the following affected routes still work:
* Log in
* Sign up
* Request password reset
* Change email
* Change privilege level
* Create child account
=> Make email equals check case insensitive

api/src/main/java/com/codeforcommunity/api/IImportProcessor.java, api/src/main/java/com/codeforcommunity/dto/imports/ImportTreeBenefitsRequest.java, api/src/main/java/com/codeforcommunity/dto/imports/ImportTreeSpeciesRequest.java, api/src/main/java/com/codeforcommunity/dto/imports/TreeBenefitImport.java, api/src/main/java/com/codeforcommunity/dto/imports/TreeSpeciesImport.java, api/src/main/java/com/codeforcommunity/dto/site/StewardshipActivity.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ImportRouter.java, persist/src/main/resources/db/migration/V4__AddTreeBenefits.sql, service/src/main/java/com/codeforcommunity/processor/ImportProcessorImpl.java
ClickUp ticket: https://app.clickup.com/t/1dk46gh
Add two tables, `TREE_SPECIES` and `TREE_BENEFITS`
- `TREE_SPECIES` stores data on a tree species's scientific name, common name, and [i-Tree](https://www.itreetools.org/) code (which is used to look up a tree's environmental benefits in the `TREE_BENEFITS` table explained below
- `TREE_BENEFITS` stores data on the actual environmental benefits (like the amounts of energy conserved and stormwater filtered) for a tree of a given tree species with a given diameter
Add two import routes, `importTreeSpecies` and `importTreeBenefits`, that can be used to populate the `TREE_SPECIES` and `TREE_BENEFITS` tables, respectively, with data from i-Tree
=> Add import routes for tree species and benefits and add sql migrations

api/src/main/java/com/codeforcommunity/api/IProtectedEmailerProcessor.java, api/src/main/java/com/codeforcommunity/dto/emailer/LoadTemplateResponse.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedEmailerRouter.java, service/src/main/java/com/codeforcommunity/ServiceMain.java, service/src/main/java/com/codeforcommunity/processor/ProtectedEmailerProcessorImpl.java, service/src/main/java/com/codeforcommunity/requester/S3Requester.java
Allows admins to load existing email templates (retrieve the name, html content, author) in the email-templates folder of the sftt-user-uploads bucket
First checks if the file exists with doesObjectExist; however instead of returning false if the file does not exist, it throws an exception (seems to come from trying to access metadata) for a 403 forbidden error. Tried to enable attribute permissions on the bucket but doesn't work. Might have to instantiate S3 client with credentials for it to work? Works fine (returns true) with the file does actually exist.
There might be a better workaround, but I catch the S3 exception and throw an InvaliURLException instead.
Making a GET request …
=> load email tempalte first iter

service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
[GH Projects Ticket](https://github.com/orgs/Code-4-Community/projects/15/views/1?pane=issue&itemId=30450878)
A user shouldn't be able to adopt a tree, name it something, and unadopt it while keeping its name, especially since there isn't a dedicated tree name review process and users can name any tree they adopt to anything they want atm.
In both the unadopt and force unadopt routes, in addition to unadopting the specified site, query its latest site entry and reset its name (i.e. change it back to `null`).
Manually verified that unadopting or force unadopting a tree sets the name of its latest site entry to `null`
=> Reset tree name when tree is unadopted or force unadopted

api/src/main/java/com/codeforcommunity/api/IProtectedEmailerProcessor.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedEmailerRouter.java, service/src/main/java/com/codeforcommunity/processor/ProtectedEmailerProcessorImpl.java, service/src/main/java/com/codeforcommunity/requester/S3Requester.java
Allows admins to delete existing email templates in the email-templates folder of the sftt-user-uploads bucket
First checks if the file exists with `doesObjectExist`; however instead of returning `false` if the file does not exist, it throws an exception (seems to come from trying to access metadata) for a 403 forbidden error. Tried to enable attribute permissions on the bucket but doesn't work. Might have to instantiate S3 client with credentials for it to work? Works fine (returns `true`) with the file does actually exist.
There might be a better workaround, but I catch the S3 exception and throw an `InvaliURLException` instead.
Calling a POST request `http://localhost:8081/api/v1/protected/emailer/delete_template/[some existing …
=> Ot.delete template

api/src/main/java/com/codeforcommunity/exceptions/NoTreePresentException.java, api/src/main/java/com/codeforcommunity/rest/FailureHandler.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java
Resolves #187 
- Adopting sites now checks if the associated entry has a tree present, throws an exception if not
- Correctly returns a 400 and doesn't adopt the site when attempting to adopt a site with no tree present 
- Correctly returns a 200 and adopts the site when attempting to adopt a site with a tree present
=> add tree presence checking

api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java, api/src/main/java/com/codeforcommunity/dto/imports/TreeSpeciesImport.java, api/src/main/java/com/codeforcommunity/dto/site/SiteEntry.java, api/src/main/java/com/codeforcommunity/dto/site/SiteEntryImage.java, api/src/main/java/com/codeforcommunity/exceptions/NoTreePresentException.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
Resolves #203 
Allows admins to approve site images with a specified image id.
Changes the approval status of the image with the given id to `APPROVED` regardless of the previous status.
Credit to @nalinikantheti for doing all the programming
Tested on postman to make sure that uploaded images switch to `APPROVED`
=> Tonk.approve site image

api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java, api/src/main/java/com/codeforcommunity/dto/site/SiteEntryImage.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java, api/src/main/java/com/codeforcommunity/rest/subrouter/SiteRouter.java, service/src/main/java/com/codeforcommunity/processor/ProtectedEmailerProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java, service/src/main/java/com/codeforcommunity/requester/S3Requester.java, service/src/main/java/com/codeforcommunity/requester/TreeBenefitsCalculator.java
Resolves #202
adds a way for devs to get all unapproved images
retrieves all images from SITE_IMAGES table with SUBMITTED approval status, so adding another enum in the future may break
postman check for http://localhost:8081/api/v1/protected/sites/unapproved_images
=> Knot.get unapproved images

api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java, api/src/main/java/com/codeforcommunity/dto/emailer/EmailAttachment.java, api/src/main/java/com/codeforcommunity/dto/neighborhoods/SendEmailRequest.java, api/src/main/java/com/codeforcommunity/dto/site/RejectImageRequest.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java, common/src/main/java/com/codeforcommunity/email/EmailOperations.java, common/src/main/resources/emails/RejectImageEmail.html, common/src/main/resources/properties/server.properties.example, service/src/main/java/com/codeforcommunity/ServiceMain.java, service/src/main/java/com/codeforcommunity/processor/ProtectedNeighborhoodsProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java, service/src/main/java/com/codeforcommunity/requester/Emailer.java
Resolves #219 
This allows the admins to send rejection email to the users who uploaded inappropriate images. 
We added a new email template "RejectImageEmail.html" to be used for image rejection email. 
Note that it will only send email when a rejection reason is given. When a reason is not given, it will delete the user image in database by using deleteSiteImage without sending the email.
=> Clot.reject image

api/src/main/java/com/codeforcommunity/dto/site/ReportSiteRequest.java, service/src/main/java/com/codeforcommunity/requester/Emailer.java
Minor tweak to site reporting route - makes the description optional, and uses a default description if none is given
Main PR: https://github.com/Code-4-Community/speak-for-the-trees-frontend/pull/355
Verified description gets replaced with default if not given:
=> Ah.site reporting edit

api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java, persist/src/main/resources/db/migration/V6_1__AddEntryDeletedAt.sql, service/src/main/java/com/codeforcommunity/processor/MapProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java
Resolves #211 
Allow admins to delete site entries, such as if they are old/obsolete
- Adds the `deleted_at` column to the `site_entries` table
- Adds a route to soft-delete entries by setting the `deleted_at` column
- Update the get site route to only fetch non-deleted entries
- Verified that deleting the route set the `deleted_at` field
- Verified that the route returns an error if there are no other entries
- Verified on the site that deleted entries don't show up
=> Implement Site Entry Deleting

api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java, api/src/main/java/com/codeforcommunity/dto/emailer/EmailAttachment.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java, common/src/main/java/com/codeforcommunity/email/EmailOperations.java, node_modules/.package-lock.json, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java, service/src/main/java/com/codeforcommunity/requester/Emailer.java, service/src/main/java/com/codeforcommunity/requester/S3Requester.java, service/target 2/surefire-reports/com.codeforcommunity.processor.ReservationProcessorImplTest.txt
Resolves #228 
Attaches the rejected image to the rejection email sent.
Directly passes the s3objectInputStream to a ByteArrayDataSource to construct an AttachmentResource.
Abstracts some email construction in EmailOperations.java for single and multiple recipient emails into helpers to allow for optional email attachments.
Also makes a rejection reason optional after #231 
Ensured that rejecting both jpeg and png image correctly attaches in the email
=> Ot.rejected image

api/pom.xml, api/src/main/java/com/codeforcommunity/api/IProtectedEmailerProcessor.java, api/src/main/java/com/codeforcommunity/api/IProtectedSiteProcessor.java, api/src/main/java/com/codeforcommunity/dto/emailer/EmailAttachment.java, api/src/main/java/com/codeforcommunity/dto/neighborhoods/SendEmailRequest.java, api/src/main/java/com/codeforcommunity/dto/site/FilterSiteImageRequest.java, api/src/main/java/com/codeforcommunity/dto/site/FilterSiteImageResponse.java, api/src/main/java/com/codeforcommunity/dto/site/ManyAddSiteEntriesRequest.java, api/src/main/java/com/codeforcommunity/dto/site/ManyEditSitesRequest.java, api/src/main/java/com/codeforcommunity/dto/site/RejectImageRequest.java, api/src/main/java/com/codeforcommunity/rest/ApiRouter.java, api/src/main/java/com/codeforcommunity/rest/IRouter.java, api/src/main/java/com/codeforcommunity/rest/IpThrottlingFilter.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedEmailerRouter.java, api/src/main/java/com/codeforcommunity/rest/subrouter/ProtectedSiteRouter.java, common/src/main/java/com/codeforcommunity/email/EmailOperations.java, pom.xml, service/src/main/java/com/codeforcommunity/ServiceMain.java, service/src/main/java/com/codeforcommunity/processor/MapProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/ProtectedEmailerProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/ProtectedNeighborhoodsProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/ProtectedSiteProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/SiteProcessorImpl.java, service/src/main/java/com/codeforcommunity/processor/TeamsProcessorImpl.java, service/src/main/java/com/codeforcommunity/requester/Emailer.java, service/src/main/java/com/codeforcommunity/requester/S3Requester.java
Implements server-side IP-specific token bucket API throttling to prevent server overload from massive popularity or DOS attack.
IpThrottlingFilter class instance acts as a VertX handler and intercepts all API calls before they get forwarded to processors. Keeps a hash map of IP addresses to buckets. Adds new buckets if new IP address. Uses bucket4j library.
Currently there is only one throttling class instance, so it is a globally-aggregated token consumption per IP. If we wanted to throttle per router or per route, we would create separate filter class instances for each route(r).
These are subject to change, but initial capacity is 20 and refills tokens at 10/min greedily (1 token every 6 sec) . One API route call consumes one token.
Service main contains …
=> Ot.rate limit v2 (Bucket4j server side throttling)
